-- Cloudflare D1 Seed Script (18 Bestsellers & Reference Tables)

INSERT OR REPLACE INTO wheel_families (code, name_uk, name_en, color_hex, profile) VALUES ('floral', 'Квіткові', 'Floral', '#E879F9', 'Романтичні, пудрові, елегантні, класичні');
INSERT OR REPLACE INTO wheel_families (code, name_uk, name_en, color_hex, profile) VALUES ('oriental', 'Східні (Бурштинові)', 'Oriental / Amber', '#F59E0B', 'Чуттєві, теплі, насичені, пряні, огортаючі');
INSERT OR REPLACE INTO wheel_families (code, name_uk, name_en, color_hex, profile) VALUES ('woody', 'Деревні', 'Woody', '#10B981', 'Землянисті, строгі, глибокі, шляхетні, сухі');
INSERT OR REPLACE INTO wheel_families (code, name_uk, name_en, color_hex, profile) VALUES ('fresh', 'Свіжі', 'Fresh', '#06B6D4', 'Енергійні, чисті, яскраві, бадьорі, іскристі');

-- 2. Subfamilies
INSERT OR REPLACE INTO wheel_subfamilies (id, ring_index, family_code, name_uk, name_en, color_hex, profile, key_ingredients) VALUES ('floral_pure', 0, 'floral', 'Квіткові', 'Floral', '#F472B6', 'Свіжозрізані квіти, солодкі романтичні пелюстки', '["троянда", "жасмин", "конвалія", "півонія", "гарденія", "тубероза"]');
INSERT OR REPLACE INTO wheel_subfamilies (id, ring_index, family_code, name_uk, name_en, color_hex, profile, key_ingredients) VALUES ('floral_soft', 1, 'floral', 'М''які квіткові', 'Soft Floral', '#EC4899', 'Оксамитові, ніжні, пудрові, витончено-ностальгічні', '["ірис", "пудрові ноти", "фіалка", "альдегіди", "мускус"]');
INSERT OR REPLACE INTO wheel_subfamilies (id, ring_index, family_code, name_uk, name_en, color_hex, profile, key_ingredients) VALUES ('floral_oriental', 2, 'floral', 'Східно-квіткові', 'Floral Oriental', '#D946EF', 'Теплі квіти з пряним відтінком та пікантним шлейфом', '["флердоранж", "османтус", "гвоздика", "солодка спеція", "іланг-іланг"]');
INSERT OR REPLACE INTO wheel_subfamilies (id, ring_index, family_code, name_uk, name_en, color_hex, profile, key_ingredients) VALUES ('oriental_soft', 3, 'oriental', 'М''які східні', 'Soft Oriental', '#FB923C', 'М''які смоли, димні пахощі, приглушена тепла солодкість', '["ладан", "бензоїн", "м''яка амбра", "кардамон", "мускатний горіх"]');
INSERT OR REPLACE INTO wheel_subfamilies (id, ring_index, family_code, name_uk, name_en, color_hex, profile, key_ingredients) VALUES ('oriental_pure', 4, 'oriental', 'Східні', 'Oriental', '#F59E0B', 'Багаті, п''янкі, розкішні, огортаючі східні акорди', '["ваніль", "смоли", "боби тонка", "амбра", "опопонакс"]');
INSERT OR REPLACE INTO wheel_subfamilies (id, ring_index, family_code, name_uk, name_en, color_hex, profile, key_ingredients) VALUES ('oriental_woody', 5, 'oriental', 'Деревно-східні', 'Woody Oriental', '#D97706', 'Густі, темні, пряно-деревні з оксамитовою базою', '["пачулі", "сандал", "темний шоколад", "амброве дерево", "шафран"]');
INSERT OR REPLACE INTO wheel_subfamilies (id, ring_index, family_code, name_uk, name_en, color_hex, profile, key_ingredients) VALUES ('woody_pure', 6, 'woody', 'Деревні', 'Woods', '#059669', 'Шляхетна суха деревина, тирса, величний лісовий спокій', '["кедр", "ветивер", "дерево уд", "сандалове дерево", "гуаяк"]');
INSERT OR REPLACE INTO wheel_subfamilies (id, ring_index, family_code, name_uk, name_en, color_hex, profile, key_ingredients) VALUES ('woody_mossy', 7, 'woody', 'Мохові деревні (Шипрові)', 'Mossy Woods / Chypre', '#10B981', 'Класичний шипровий контраст: вологий мох, лісова прохолода', '["дубовий мох", "бергамот", "ладанник", "земляні ноти", "листи пачулі"]');
INSERT OR REPLACE INTO wheel_subfamilies (id, ring_index, family_code, name_uk, name_en, color_hex, profile, key_ingredients) VALUES ('woody_dry', 8, 'woody', 'Сухі деревні (Шкіряні)', 'Dry Woods / Leather', '#34D399', 'Димні, строгі, брутальні шкіряні та тютюнові відтінки', '["шкіра", "тютюн", "березовий дьоготь", "суха деревина", "дим"]');
INSERT OR REPLACE INTO wheel_subfamilies (id, ring_index, family_code, name_uk, name_en, color_hex, profile, key_ingredients) VALUES ('fresh_citrus', 9, 'fresh', 'Цитрусові', 'Citrus', '#06B6D4', 'Іскристі, яскраві, сонячні, соковиті та бадьорі', '["лимон", "бергамот", "мандарин", "грейпфрут", "лайм", "вербена"]');
INSERT OR REPLACE INTO wheel_subfamilies (id, ring_index, family_code, name_uk, name_en, color_hex, profile, key_ingredients) VALUES ('fresh_aquatic', 10, 'fresh', 'Водні (Акватичні)', 'Water / Aquatic', '#0EA5E9', 'Прозорі, прохолодні, озонові, наче подих океану', '["морська сіль", "калон", "водорості", "морський бриз", "латаття"]');
INSERT OR REPLACE INTO wheel_subfamilies (id, ring_index, family_code, name_uk, name_en, color_hex, profile, key_ingredients) VALUES ('fresh_green', 11, 'fresh', 'Зелені', 'Green', '#38BDF8', 'Хрусткі, природні, наче зім''яте в руках свіже листя', '["скошена трава", "гальбанум", "листя фіалки", "м''ята", "зелений чай"]');
INSERT OR REPLACE INTO wheel_subfamilies (id, ring_index, family_code, name_uk, name_en, color_hex, profile, key_ingredients) VALUES ('fresh_fruity', 12, 'fresh', 'Фруктові', 'Fruity', '#818CF8', 'Солодкі, грайливі, десертні свіжі фрукти та ягоди', '["чорна смородина", "персик", "яблуко", "груша", "малина", "лічі"]');
INSERT OR REPLACE INTO wheel_subfamilies (id, ring_index, family_code, name_uk, name_en, color_hex, profile, key_ingredients) VALUES ('fresh_aromatic', 13, 'fresh', 'Ароматичні (Фужерні)', 'Aromatic / Fougère', '#A78BFA', 'Трав''янисто-пряні, вишукані, сполучна ланка між свіжістю і лісом', '["лаванда", "розмарин", "шавлія", "базилік", "чебрець"]');

-- 3. Brands
INSERT OR REPLACE INTO brands (id, name) VALUES ('carolina_herrera', 'Carolina Herrera');
INSERT OR REPLACE INTO brands (id, name) VALUES ('chanel', 'Chanel');
INSERT OR REPLACE INTO brands (id, name) VALUES ('dior', 'Dior');
INSERT OR REPLACE INTO brands (id, name) VALUES ('giorgio_armani', 'Giorgio Armani');
INSERT OR REPLACE INTO brands (id, name) VALUES ('kilian', 'Kilian');
INSERT OR REPLACE INTO brands (id, name) VALUES ('lancome', 'Lancôme');
INSERT OR REPLACE INTO brands (id, name) VALUES ('mfk', 'Maison Francis Kurkdjian');
INSERT OR REPLACE INTO brands (id, name) VALUES ('tom_ford', 'Tom Ford');
INSERT OR REPLACE INTO brands (id, name) VALUES ('ysl', 'Yves Saint Laurent');

-- 4. Fragrances
INSERT OR REPLACE INTO fragrances (id, brand_id, brand_name, name, gender, concentration, primary_subfamily_id, family_code, top_notes, heart_notes, base_notes, price_uah, product_sku, product_url, image_url) VALUES ('lancome_la_vie_est_belle', 'lancome', 'Lancôme', 'La Vie Est Belle', 'female', 'Eau de Parfum', 'oriental_pure', 'oriental', '["чорна смородина", "груша"]', '["ірис", "жасмин", "флердоранж"]', '["праліне", "ваніль", "пачулі", "боби тонка"]', 4850.0, 'LAN-LVEB-50', 'https://www.brocard.ua/ua/product/parfumovana-voda-lancome-la-vie-est-belle', 'https://images.unsplash.com/photo-1541643600914-78b084683601?auto=format&fit=crop&w=400&q=80');
INSERT OR REPLACE INTO fragrances (id, brand_id, brand_name, name, gender, concentration, primary_subfamily_id, family_code, top_notes, heart_notes, base_notes, price_uah, product_sku, product_url, image_url) VALUES ('lancome_idole', 'lancome', 'Lancôme', 'Idôle', 'female', 'Eau de Parfum', 'floral_pure', 'floral', '["бергамот", "груша", "рожевий перець"]', '["троянда", "травнева троянда", "індійський жасмин"]', '["білий мускус", "ваніль", "пачулі", "кедр"]', 4420.0, 'LAN-IDL-50', 'https://www.brocard.ua/ua/product/parfumovana-voda-lancome-idole', 'https://images.unsplash.com/photo-1588405748880-12d1d2a59f75?auto=format&fit=crop&w=400&q=80');
INSERT OR REPLACE INTO fragrances (id, brand_id, brand_name, name, gender, concentration, primary_subfamily_id, family_code, top_notes, heart_notes, base_notes, price_uah, product_sku, product_url, image_url) VALUES ('lancome_tresor', 'lancome', 'Lancôme', 'Trésor', 'female', 'Eau de Parfum', 'floral_pure', 'floral', '["персик", "абрикос", "бузок", "бергамот", "конвалія"]', '["троянда", "ірис", "геліотроп", "жасмин"]', '["сандал", "мускус", "амбра", "ваніль"]', 4990.0, 'LAN-TRS-50', 'https://www.brocard.ua/ua/product/parfumovana-voda-lancome-tresor', 'https://images.unsplash.com/photo-1594035910387-fea47794261f?auto=format&fit=crop&w=400&q=80');
INSERT OR REPLACE INTO fragrances (id, brand_id, brand_name, name, gender, concentration, primary_subfamily_id, family_code, top_notes, heart_notes, base_notes, price_uah, product_sku, product_url, image_url) VALUES ('carolina_herrera_good_girl', 'carolina_herrera', 'Carolina Herrera', 'Good Girl', 'female', 'Eau de Parfum', 'oriental_pure', 'oriental', '["мигдаль", "кава", "бергамот", "лимон"]', '["тубероза", "жасмин самбак", "флердоранж", "ірис"]', '["боби тонка", "какао", "ваніль", "праліне", "сандал", "мускус", "амбра", "пачулі", "кедр"]', 5200.0, 'CH-GG-50', 'https://www.brocard.ua/ua/product/parfumovana-voda-carolina-herrera-good-girl', 'https://images.unsplash.com/photo-1523293182086-7651a899d37f?auto=format&fit=crop&w=400&q=80');
INSERT OR REPLACE INTO fragrances (id, brand_id, brand_name, name, gender, concentration, primary_subfamily_id, family_code, top_notes, heart_notes, base_notes, price_uah, product_sku, product_url, image_url) VALUES ('carolina_herrera_very_good_girl', 'carolina_herrera', 'Carolina Herrera', 'Very Good Girl', 'female', 'Eau de Parfum', 'floral_pure', 'floral', '["червона смородина", "лічі"]', '["троянда"]', '["ваніль", "ветивер"]', 5400.0, 'CH-VGG-50', 'https://www.brocard.ua/ua/product/parfumovana-voda-carolina-herrera-very-good-girl', 'https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?auto=format&fit=crop&w=400&q=80');
INSERT OR REPLACE INTO fragrances (id, brand_id, brand_name, name, gender, concentration, primary_subfamily_id, family_code, top_notes, heart_notes, base_notes, price_uah, product_sku, product_url, image_url) VALUES ('carolina_herrera_bad_boy', 'carolina_herrera', 'Carolina Herrera', 'Bad Boy', 'male', 'Eau de Toilette', 'oriental_woody', 'oriental', '["білий перець", "чорний перець", "бергамот"]', '["шавлія", "кедр"]', '["боби тонка", "какао", "амброве дерево"]', 4750.0, 'CH-BB-100', 'https://www.brocard.ua/ua/product/tualetna-voda-carolina-herrera-bad-boy', 'https://images.unsplash.com/photo-1527799820374-dcf8d9d4a388?auto=format&fit=crop&w=400&q=80');
INSERT OR REPLACE INTO fragrances (id, brand_id, brand_name, name, gender, concentration, primary_subfamily_id, family_code, top_notes, heart_notes, base_notes, price_uah, product_sku, product_url, image_url) VALUES ('chanel_coco_mademoiselle', 'chanel', 'Chanel', 'Coco Mademoiselle', 'female', 'Eau de Parfum', 'oriental_pure', 'oriental', '["апельсин", "мандарин", "бергамот", "флердоранж"]', '["турецька троянда", "жасмин", "мімоза", "іланг-іланг"]', '["пачулі", "білий мускус", "ваніль", "ветивер", "боби тонка", "опопонакс"]', 6800.0, 'CHL-CCM-50', 'https://www.brocard.ua/ua/product/chanel-coco-mademoiselle', 'https://images.unsplash.com/photo-1547887537-6158d64c35b3?auto=format&fit=crop&w=400&q=80');
INSERT OR REPLACE INTO fragrances (id, brand_id, brand_name, name, gender, concentration, primary_subfamily_id, family_code, top_notes, heart_notes, base_notes, price_uah, product_sku, product_url, image_url) VALUES ('chanel_bleu_de_chanel', 'chanel', 'Chanel', 'Bleu de Chanel', 'male', 'Eau de Parfum', 'woody_pure', 'woody', '["грейпфрут", "лимон", "м''ята", "рожевий перець", "бергамот"]', '["імбир", "мускатний горіх", "жасмин"]', '["ладан", "ветивер", "кедр", "сандал", "пачулі", "білий мускус"]', 6400.0, 'CHL-BDC-50', 'https://www.brocard.ua/ua/product/chanel-bleu-de-chanel', 'https://images.unsplash.com/photo-1523293182086-7651a899d37f?auto=format&fit=crop&w=400&q=80');
INSERT OR REPLACE INTO fragrances (id, brand_id, brand_name, name, gender, concentration, primary_subfamily_id, family_code, top_notes, heart_notes, base_notes, price_uah, product_sku, product_url, image_url) VALUES ('tom_ford_tobacco_vanille', 'tom_ford', 'Tom Ford', 'Tobacco Vanille', 'unisex', 'Eau de Parfum', 'oriental_pure', 'oriental', '["тютюн", "прянощі"]', '["боби тонка", "ваніль", "какао"]', '["суха деревина", "смоли"]', 11500.0, 'TF-TBV-50', 'https://www.brocard.ua/ua/product/tom-ford-tobacco-vanille', 'https://images.unsplash.com/photo-1594035910387-fea47794261f?auto=format&fit=crop&w=400&q=80');
INSERT OR REPLACE INTO fragrances (id, brand_id, brand_name, name, gender, concentration, primary_subfamily_id, family_code, top_notes, heart_notes, base_notes, price_uah, product_sku, product_url, image_url) VALUES ('tom_ford_oud_wood', 'tom_ford', 'Tom Ford', 'Oud Wood', 'unisex', 'Eau de Parfum', 'woody_pure', 'woody', '["кардамон", "рожевий перець"]', '["уд", "дерево уд", "сандал", "ветивер"]', '["боби тонка", "ваніль", "амбра"]', 11900.0, 'TF-OW-50', 'https://www.brocard.ua/ua/product/tom-ford-oud-wood', 'https://images.unsplash.com/photo-1588405748880-12d1d2a59f75?auto=format&fit=crop&w=400&q=80');
INSERT OR REPLACE INTO fragrances (id, brand_id, brand_name, name, gender, concentration, primary_subfamily_id, family_code, top_notes, heart_notes, base_notes, price_uah, product_sku, product_url, image_url) VALUES ('tom_ford_lost_cherry', 'tom_ford', 'Tom Ford', 'Lost Cherry', 'unisex', 'Eau de Parfum', 'floral_pure', 'floral', '["вишня", "черешня", "гіркий мигдаль"]', '["троянда", "жасмин самбак"]', '["боби тонка", "перуанський бальзам", "сандал", "ветивер", "кедр", "пачулі", "ваніль"]', 13800.0, 'TF-LC-50', 'https://www.brocard.ua/ua/product/tom-ford-lost-cherry', 'https://images.unsplash.com/photo-1541643600914-78b084683601?auto=format&fit=crop&w=400&q=80');
INSERT OR REPLACE INTO fragrances (id, brand_id, brand_name, name, gender, concentration, primary_subfamily_id, family_code, top_notes, heart_notes, base_notes, price_uah, product_sku, product_url, image_url) VALUES ('ysl_black_opium', 'ysl', 'Yves Saint Laurent', 'Black Opium', 'female', 'Eau de Parfum', 'oriental_pure', 'oriental', '["груша", "рожевий перець", "флердоранж"]', '["кава", "жасмин", "гіркий мигдаль"]', '["ваніль", "пачулі", "кедр", "кашемірове дерево"]', 4980.0, 'YSL-BO-50', 'https://www.brocard.ua/ua/product/yves-saint-laurent-black-opium', 'https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?auto=format&fit=crop&w=400&q=80');
INSERT OR REPLACE INTO fragrances (id, brand_id, brand_name, name, gender, concentration, primary_subfamily_id, family_code, top_notes, heart_notes, base_notes, price_uah, product_sku, product_url, image_url) VALUES ('ysl_libre', 'ysl', 'Yves Saint Laurent', 'Libre', 'female', 'Eau de Parfum', 'fresh_aromatic', 'fresh', '["лаванда", "мандарин", "чорна смородина", "петитгрейн"]', '["лаванда", "флердоранж", "жасмин"]', '["ваніль", "мускус", "кедр", "сіра амбра"]', 5150.0, 'YSL-LIB-50', 'https://www.brocard.ua/ua/product/yves-saint-laurent-libre', 'https://images.unsplash.com/photo-1547887537-6158d64c35b3?auto=format&fit=crop&w=400&q=80');
INSERT OR REPLACE INTO fragrances (id, brand_id, brand_name, name, gender, concentration, primary_subfamily_id, family_code, top_notes, heart_notes, base_notes, price_uah, product_sku, product_url, image_url) VALUES ('dior_sauvage', 'dior', 'Dior', 'Sauvage', 'male', 'Eau de Toilette', 'fresh_aromatic', 'fresh', '["калабрійський бергамот", "перець"]', '["лаванда", "сичуанський перець", "ветивер", "пачулі", "герань"]', '["амброксан", "кедр", "лабданум"]', 5600.0, 'DIOR-SVG-60', 'https://www.brocard.ua/ua/product/dior-sauvage', 'https://images.unsplash.com/photo-1523293182086-7651a899d37f?auto=format&fit=crop&w=400&q=80');
INSERT OR REPLACE INTO fragrances (id, brand_id, brand_name, name, gender, concentration, primary_subfamily_id, family_code, top_notes, heart_notes, base_notes, price_uah, product_sku, product_url, image_url) VALUES ('dior_fahrenheit', 'dior', 'Dior', 'Fahrenheit', 'male', 'Eau de Toilette', 'woody_pure', 'woody', '["лаванда", "мандарин", "глід", "кедр", "бергамот", "ромашка", "лимон"]', '["мускатний горіх", "жимолость", "гвоздика", "сандал", "листя фіалки", "жасмин", "конвалія", "кедр"]', '["шкіра", "боби тонка", "амбра", "пачулі", "мускус", "ветивер"]', 5300.0, 'DIOR-FHR-50', 'https://www.brocard.ua/ua/product/dior-fahrenheit', 'https://images.unsplash.com/photo-1588405748880-12d1d2a59f75?auto=format&fit=crop&w=400&q=80');
INSERT OR REPLACE INTO fragrances (id, brand_id, brand_name, name, gender, concentration, primary_subfamily_id, family_code, top_notes, heart_notes, base_notes, price_uah, product_sku, product_url, image_url) VALUES ('armani_acqua_di_gio', 'giorgio_armani', 'Giorgio Armani', 'Acqua Di Giò', 'male', 'Eau de Toilette', 'fresh_aquatic', 'fresh', '["лайм", "лимон", "бергамот", "жасмин", "апельсин", "мандарин", "неролі"]', '["морські ноти", "жасмин", "калон", "персик", "фрезія", "гіацинт", "розмарин"]', '["білий мускус", "кедр", "дубовий мох", "пачулі", "амбра"]', 4600.0, 'GA-ADG-50', 'https://www.brocard.ua/ua/product/giorgio-armani-acqua-di-gio', 'https://images.unsplash.com/photo-1541643600914-78b084683601?auto=format&fit=crop&w=400&q=80');
INSERT OR REPLACE INTO fragrances (id, brand_id, brand_name, name, gender, concentration, primary_subfamily_id, family_code, top_notes, heart_notes, base_notes, price_uah, product_sku, product_url, image_url) VALUES ('mfk_baccarat_rouge_540', 'mfk', 'Maison Francis Kurkdjian', 'Baccarat Rouge 540', 'unisex', 'Eau de Parfum', 'floral_pure', 'floral', '["шафран", "жасмин"]', '["амброве дерево", "сіра амбра"]', '["ялинова смола", "кедр"]', 12900.0, 'MFK-BR540-70', 'https://www.brocard.ua/ua/product/maison-francis-kurkdjian-baccarat-rouge-540', 'https://images.unsplash.com/photo-1594035910387-fea47794261f?auto=format&fit=crop&w=400&q=80');
INSERT OR REPLACE INTO fragrances (id, brand_id, brand_name, name, gender, concentration, primary_subfamily_id, family_code, top_notes, heart_notes, base_notes, price_uah, product_sku, product_url, image_url) VALUES ('kilian_angels_share', 'kilian', 'Kilian', 'Angels'' Share', 'unisex', 'Eau de Parfum', 'oriental_pure', 'oriental', '["коньяк"]', '["кориця", "боби тонка", "дуб"]', '["праліне", "ваніль", "сандал"]', 10500.0, 'KIL-ASH-50', 'https://www.brocard.ua/ua/product/kilian-angels-share', 'https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?auto=format&fit=crop&w=400&q=80');
